site_name: SimLogica.com
site_description: The home of Blocker Smart Call Controller and Antispam App.
site_author: SimLogica.com
site_url: https://simlogica.github.io/

theme:
  name: material
  custom_dir: overrides
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: deep orange
  font:
    text: Inter
    code: Red Hat Mono
  logo: common/images/simlogica.png
  favicon: common/images/simlogica.png
  features:
    - navigation.footer
    # - navigation.instant   # Transforms the site into a Single Page Application (SPA) for instant loading
    # - navigation.tracking  # Updates the URL with the anchor tag as the user scrolls

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2026 SimLogica.com

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

nav:
  - Blocker App: index.md
  - FAQ: faq/index.md
  - Configuring Blocker: configure/index.md
  - Privacy Policy: privacy/index.md
  - Terms of Use: terms/index.md

plugins:
  - social
  - search
  - i18n:
      docs_structure: suffix      # files like index.pt-BR.md, index.pt-PT.md
      reconfigure_material: true  # autoconfigures Material's lang & language switcher
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: pt
          name: Português
          build: true
          site_description: Criadores do Blocker Controle Inteligente de Chamadas e Antispam App.
          nav_translations:
            Blocker App: Blocker App
            Configuring Blocker: Configurando o Blocker
            FAQ: Dúvidas Frequentes
            Privacy Policy: Política de Privacidade
            Terms of Use: Termos de Uso
  - minify:
      minify_html: true
  - redirects: # Redirect URLS
      redirect_maps:
        # TO BE REMOVED!!
        "blocker.md": "index.md"
        "pt/blocker.md": "index.md"
        "r-privacy.md": "privacy/index.md" # Google Play redirects here
        "r-terms.md": "terms/index.md" # Google Play redirects here
        # REDIRECTS
        "r/blocker-android/help.md": "index.md" # Android App NEED HELP BUTTON redirects here
        "r/blocker-android/privacy.md": "privacy/index.md" # Android App PRIVACY BUTTON redirects here
        "r/blocker-android/share.md": "index.md" # Android App SHARE BUTTON redirects here
        "r/blocker-googleplay/privacy.md": "privacy/index.md" # Google Play redirects here
        "r/blocker-googleplay/terms.md": "terms/index.md" # Google Play redirects here (??? could not confirm..) -------------------!!!!!!!!!!!
