site_name: SimLogica.com

site_url: https://simlogica.github.io

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: deep orange
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/simlogica.png
  favicon: assets/simlogica.png
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2026 SimLogica.com

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

nav:
  - Blocker App: index.md
  - Configuring Blocker: configure.md
  - FAQ: faq.md
  - Privacy Policy: privacy.md
  - Terms of Use: terms.md

plugins:
  - search
  - redirects: # Redirect URLS
      redirect_maps:
        "r-blocker-android.md": "index.md" # Android App redirect URL
